### PR TITLE
Partial fix PostgreSQL cache item expiration

### PR DESCRIPTION
**Pull request by bjornharrtell**

### CODE REVIEW

**Comment by bjornharrtell** [comment]
@Revsgaard I'm confused - you have RemoveAllExpired for the PgTenantDataRepository class and a background service but not for the cache provider (so this fix will not be enough). And also, I can find no logic that indicates that expiration is used for tenant data items?

**Comment by Revsgaard** [comment]
Thank you, you are correct. I have added the RemoveAllExpiredAsync method in PostgreSqlCacheProvider to remove expired cache items. 

Commit https://github.com/ITfoxtec/FoxIDs/commit/0fa3883a83273a40cf512552a94c90c5249b11ee

TTL is used in the tenant data items: RefreshTokenTtlGrant and AuthCodeTtlGrant. I have added the [expires parameter in PgTenantDataRepository](https://github.com/ITfoxtec/FoxIDs/blob/1.4.x-development/src/FoxIDs.Shared/Repository/PostgreSql/PgTenantDataRepository.cs#L132).

@bjornharrtell would it be possible to filter out expired items on load (get, exists, count) and even maybe delete expired items?

**Comment by bjornharrtell** [comment]
@Revsgaard I considered adding deletion on get but decided it's too heavy handed to run on every get operation. Filtering out seems reasonable though, I will considering it.

**Comment by Revsgaard** [comment]
@bjornharrtell sounds absolutely right, filtering out sounds like the correct solution.

**Comment by bjornharrtell** [comment]
Tracking by https://github.com/bjornharrtell/PgKeyValueDB/issues/1

**Pull request merged**
