### PR TITLE
Upgrade and improve PgKeyValueDB usage

### PR DESCRIPTION
**Pull request by bjornharrtell**
## TODO

* [x] Use stable version
* [x] Pagination
* [x] Count and removal filtering

ref https://github.com/ITfoxtec/FoxIDs/issues/986 and https://github.com/ITfoxtec/FoxIDs/issues/783

### CODE REVIEW

**Comment by bjornharrtell** [comment]
I'm uncertain about pagination.. seems it's assumed to be stateful using a token (but simplified approach in file system repository?) but I think I can only do it stateless and as such will be incorrect if the result is changed due to updates between requests. Is still an acceptable solution for pagination @Revsgaard ?

**Comment by Revsgaard** [comment]
It is also stateless in the MongoDB implementation, I think it is okay to do et stateless.
The name of the `paginationToken` is ore or less from CosmosDB, where it is called `ContinuationToken`. Is there a better name insted of `paginationToken`?

**Comment by bjornharrtell** [comment]
Not sure, it seems implementation specific and could mean token or page number or something else so I think it might be ok. I'll see if I can understand how to implement it in this case.

**Comment by bjornharrtell** [comment]
@Revsgaard I've implemented but not tested. I'm considering adding means to test against real PG as I do here https://github.com/bjornharrtell/PgKeyValueDB/blob/6f1e679cb183637a12b67c98be47abc58f72b0c6/test/PgKeyValueDB.Tests/PgKeyValueDBTest.cs#L16 (it uses https://github.com/mysticmind/mysticmind-postgresembed) but not sure I will be able to finish it at this time.

**Comment by bjornharrtell** [comment]
@Revsgaard did some tests and the expression conversion is not good enough. I'll see what I can do.

**Comment by bjornharrtell** [comment]
@Revsgaard looks like it works now (however, pagination is not really tested)

**Comment by Revsgaard** [comment]
I think it's best if the PG version can be dynamic, but if needed, it can be part of the PG configuration next to the connection string.

Sounds like good progress :)

**Comment by Revsgaard** [comment]
I mean the version number in your code  `pg = new PgServer("16.2.0", clearWorkingDirOnStart: true, clearInstanceDirOnStop: true);` https://github.com/bjornharrtell/PgKeyValueDB/blob/6f1e679cb183637a12b67c98be47abc58f72b0c6/test/PgKeyValueDB.Tests/PgKeyValueDBTest.cs#L16

**Comment by bjornharrtell** [comment]
@Revsgaard that is only tests? (it runs them against embedded PostgreSQL with specified version, it is not in any way included in the nuget)

**Comment by Revsgaard** [comment]
Cool, I'll review/merge next week :)

**Comment by bjornharrtell** [comment]
@Revsgaard don't forget about this :)

**Comment by Revsgaard** [comment]
Sorry I have been very busy, I promise to do it next week :)

**Comment by bjornharrtell** [comment]
Yes the new version is not backward compatible.

Current investigation for the listing/filter issue is that ForUsage for tenant is expected to be true but is persisted false.

**Pull request merged**
