### PR TITLE
Add and implement IDistributedCacheProvider to allow for future alternative implementations

### PR DESCRIPTION
**Pull request by bjornharrtell**
ref https://github.com/ITfoxtec/FoxIDs/issues/742

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Note that this doesn't fully allow to replace Redis with something else because of https://github.com/ITfoxtec/FoxIDs/issues/742#issuecomment-1975180885.

**Comment by bjornharrtell** [comment]
I've now also replaced IDistributedCache. If ICacheProvider needs to be cross process I will rename it to IDistributedCacheProvider and rework the MemoryCacheProvider into SQLiteCacheProvider and possibly a PostgreSQLCacheProvider.

**Comment by Revsgaard** [comment]
The cache needs to be distributed because it is used by instances of both the IdP site and Control site. It caches sequence, data for performance, and counts (e.g. invalid password attempt).
The data caches is cleaned by the Control site when data is updated.

**Comment by Revsgaard** [comment]
The cache is used to implement a queues in:
https://github.com/ITfoxtec/FoxIDs/blob/master/src/FoxIDs.Control/Logic/Queues/DownPartyAllowUpPartiesQueueLogic.cs#L121
https://github.com/ITfoxtec/FoxIDs/blob/master/src/FoxIDs.Control/Logic/Queues/DownPartyAllowUpPartiesQueueLogic.cs#L124

**Comment by Revsgaard** [comment]
The cache is used to send email verification codes in:
https://github.com/ITfoxtec/FoxIDs/blob/master/src/FoxIDs/Logic/Tracks/AccountActionLogic.cs

**Comment by Revsgaard** [comment]
The cache is used to count (e.g. invalid password attempt) in:
https://github.com/ITfoxtec/FoxIDs/blob/master/src/FoxIDs/Logic/Login/FailingLoginLogic.cs

**Comment by bjornharrtell** [comment]
Ok so I've now removed the in memory variant as it will not be usable unless we make FoxIDs capable of running as single process.

This PR is complete in the sense that it abstracts use of Redis as generic interface IDistributedCacheProvider. Only Redis is implememented for now.

I've taken as much care as possible to not break anything but I suppose regressions are always possible. As I'm currently unable to verify involved functionality I would recommend testing before merge or waiting until I'm (hopefully) capable of doing such tests myself.

**Comment by bjornharrtell** [comment]
@Revsgaard I think I might have fixed some small bugs in this PR with regard to the expiry of up party metadata failure counts which appeared to not be set properly in the old direct Redis implemementation.

**Comment by Revsgaard** [comment]
Thank you, it looks grate :)

What do you think about queue handling it still depends of Redis:
https://github.com/ITfoxtec/FoxIDs/blob/master/src/FoxIDs.Control/Logic/Queues/DownPartyAllowUpPartiesQueueLogic.cs#L121
https://github.com/ITfoxtec/FoxIDs/blob/master/src/FoxIDs.Control/Logic/Queues/DownPartyAllowUpPartiesQueueLogic.cs#L124

**Comment by bjornharrtell** [comment]
I suggest to make a generic interface for queue pub/sub and then plugin Redis in similar way as this PR does with the key value stuff. That would then allow to plugin alternatives like https://rebus.fm/what-is-rebus/.

**Comment by Revsgaard** [comment]
The cache code is in branch https://github.com/ITfoxtec/FoxIDs/tree/1.2.x-development-cache. 
I've gone through the code and made small changes. Tested and it works :)

**Comment by Revsgaard** [comment]
Thank you Björn.
The code will be included in the next release.

**Pull request merged**
