### PR TITLE
Increasing the length validator restrictions

### PR DESCRIPTION
**Pull request by alex-kur**
Increasing the length of party and track names from 30 to 50;
Increasing the max count of down-parties redirect URIs from 40 to 200;

### CODE REVIEW

**Review by stasnovogursky — COMMENTED** [review]
Hello Anders,

It would be great if U applied Alex's (my colleague) changes, cause right now, to cover our dev env we had to use 3 down-parties just to cover all possible redirect urls.

**Comment by Revsgaard** [comment]
Hi, I'll look into it.

**Comment by Revsgaard** [comment]
Login request URL: `https://foxidsxxxx.com/tenant-30/track-30/down-party-30(up-party-v1-30,up-party-v2-30,up-party-v3-30,up-party-v4-30)/_CfDJ8PCxKdBiWqNMh1jDXm1OKJaR2vWTxGAjDrcc0hurEGoSH_cC3m_MrOghmPLeXof3UuBbSzvjR7sA-WeoiCqLqmmphl3TX_rHL813_evp-7Pxmg0R6zzzWch1DMeoJHLboHA3qDqU8zGnsw6dEL_1P0uAvZPBT4JanFJ4Bfxk9EI_i0dB6NCePCHAaKJgIbro9WvwmKAHgaP5acmg9cq6UA6GHMy9-CVEq5xb7V-y45Cu6B8pflaBXR/YxE5EPBbmnv07MCMLxQnFVszsgYsxDYPy5rd3DeJ0b5B7JVGf6m60_`

- Domain estimated max: 300
- Sequence string estimated max: 600

URL length with different tenant, track and party character length:
- 30 character: 300 + 30 + 30 + 30 + (4*30) + 600 = 1110
- 50 character: 300 + 50 + 50 + 50 + (4*50) + 600 = 1250

Browsers' URL length general limit: 2048

The URLs are still below the general browser limit and it should be okay to increase the maximum length for tenant, track and parties to 50 characters.

**Comment by Revsgaard** [comment]
Change pars of version [1.1.2](https://github.com/ITfoxtec/FoxIDs/releases/tag/1.1.2).

**Pull request closed without merging**
