### PR TITLE
Pluggable queue backend

### PR DESCRIPTION
**Pull request by bjornharrtell**
ref https://github.com/ITfoxtec/FoxIDs/issues/742

### CODE REVIEW

**Comment by bjornharrtell** [comment]
@Revsgaard this is an attempt to provide a generic interface for queue like functionality and plugin Redis as the default implementation. The interface is loosely modeled on similar interfaces in Azure.Messaging.ServiceBus. As with https://github.com/ITfoxtec/FoxIDs/pull/743 I'm unable to really test this at this point and I *most definitely* recommend verifying that it works before merge. I'm less certain I got this right on first attempt.

@Revsgaard a question on the existing Redis usage (which I kept as is) is that you appear to send an empty message then use a key list value to hold the data. That seems complicated and perhaps not robust? Why not send the "envelope" as the message directly and remove the use of key value?

**Comment by bjornharrtell** [comment]
Setting to draft again because I realise I do not poll for events before subscribing, the previous code did so that might regress... I will attempt add back the polling before this is ready.

**Comment by bjornharrtell** [comment]
@Revsgaard it looks like the combination of pub/sub and a queue as a value in the key value store of redis is a bit unorthodox. Normally a pub/sub patterns means that the subscriber will only get messages that happen after the subscription time. With your logic I suppose you get messages that was sent before the subscription was made. I'm not sure about the purpose of this logic, is it really needed? I don't think it cannot be implemented by a pub/sub stack  (aka message bus) only.

**Comment by bjornharrtell** [comment]
I'm wondering about the use case. It kind of looks like what you are doing is more like background async job processing, something https://www.hangfire.io/ would be a better fit for than a pub/sub message queue.

**Comment by Revsgaard** [comment]
You are right. It opdates down-party documents as a consequence of up-party documents being updated.
The code should probably be changed. Maybe just use a background.NET task...

**Comment by Revsgaard** [comment]
@bjornharrtell there can be max 2000 up-parties and 2000 down-parties in a track. And it would be okay to let the initially updating process continue the background task.

**Comment by Revsgaard** [comment]
I closed this one by mistake. But since the code probably needs to be changed to use a background task, it probably doesn't matter.

**Comment by bjornharrtell** [comment]
@Revsgaard agreed. If nothing new comes to light it should be a simple as possible implementation and will not need interface/pluggable architecture. I'm not sure I will be able to do it safely though, will you make an attempt?

**Pull request closed without merging**
